name: scrape
on:
  schedule:
    - cron: '58 16 * * *'
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r github_action/requirements.txt
      - name: Run the scraping script
        env:
          DETA_PROJECT_KEY: ${{ secrets.DETA_PROJECT_KEY }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python github_action/main.py
